#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "postiz"
name = "Postiz"
description.en = "The ultimate agentic social media scheduling tool"
description.fr = "L'outil ultime de planification agentique des réseaux sociaux"
version = "2.24.0~ynh1"

maintainers = ["CodeShakingSheep"]

[upstream]
license = "AGPL-3.0-only"
website = "https://postiz.com"
admindoc = "https://docs.postiz.com"
code = "https://github.com/gitroomhq/postiz-app"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "2000M"
ram.build = "4096M"
ram.runtime = "2048M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/gitroomhq/postiz-app/archive/refs/tags/v2.24.0.tar.gz"
    sha256 = "9e45256087b50ad58d609c998d1e2ba0772257ba6d6513c1c326de2ac3fb931b"
    autoupdate.strategy = "latest_github_release"

    [resources.sources.temporal]
    amd64.url = "https://github.com/temporalio/cli/releases/download/v1.7.2/temporal_cli_1.7.2_linux_amd64.tar.gz"
    amd64.sha256 = "e2f548af84e820b7d71f25fc6461a4e6a1ab7cdb6a80fde3c375641b0772375b"

    arm64.url = "https://github.com/temporalio/cli/releases/download/v1.7.2/temporal_cli_1.7.2_linux_arm64.tar.gz"
    arm64.sha256 = "0d60307cf036f5e29cf0d298dabc9dd62f1cce80f72cbfdbdb0e54ad7790a701"
    
    in_subdir = false
    #autoupdate.strategy = "latest_github_release"

    [resources.ports]
        main.default = 3000
        frontend.default = 4200

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx, postgresql, redis-server"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
